# Generated by Django 3.2.7 on 2021-09-12 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('category', models.CharField(choices=[('IT', 'Интернет'), ('CE', 'Культура'), ('SY', 'Общество'), ('PY', 'Политика'), ('ST', 'Спорт'), ('EY', 'Экономика')], default='IT', max_length=2, verbose_name='Категория')),
                ('img', models.ImageField(blank=True, upload_to='img/article', verbose_name='Фотография')),
                ('short_text', models.CharField(max_length=200, verbose_name='Короткий текст')),
                ('text', models.TextField(verbose_name='Текст')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Текст комментария')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.article', verbose_name='Новость')),
                ('name', models.ManyToManyField(related_name='comm_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
    ]
